# Generated by Django 4.2.7 on 2024-01-25 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonCategorys',
        ),
    ]
