version: '3.7'

services:
  theatre-db:
    image: postgres:14-alpine
    container_name: theatre-db
    volumes:
      - theatre_postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"   # Делай изоляцию на localhost
    healthcheck:
      test: pg_isready -d theatre_main -U admin
      interval: 10s
      timeout: 5s
      retries: 5

  theatre-app:
    build:
      context: .
      dockerfile: _configs/app/Dockerfile
    container_name: theatre-app
    command: bash entrypoint.sh
    volumes:
      - ./src:/theatre
      - ./src/static:/theatre/static
      - ./src/media:/theatre/media:rw
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      WAIT-HOSTS: theatre-db
    restart: always
    tty: true
    depends_on:
      - theatre-db





#  nginx:
#    build: ./nginx
#    container_name: sound_cloud_nginx
#    restart: on-failure
#    ports:
#      - "80:80"   # Порты с 3 версии, кажется, идут с кавычками
#    volumes:
#      - ./static:/static
#      - ./media:/media
#    depends_on:
#      - theatre-app

volumes:
  theatre_postgres_data:

networks:
  theatre_net:
    external: false


