version: '3.7'

services:
  theatre-app:
    build: ./
    container_name: theatre-app
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media:rw
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - theatre-db


  theatre-db:
    image: postgres:15.3-alpine
    container_name: theatre-db
    volumes:
      - theatre_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - "127.0.0.1:5432:5432"   # Делай изоляцию на localhost
    healthcheck:
      test: pg_isready -d postgres -U postgres
      interval: 10s
      timeout: 5s
      retries: 5


#  nginx:
#    build: ./nginx
#    container_name: sound_cloud_nginx
#    restart: on-failure
#    ports:
#      - "80:80"   # Порты с 3 версии, кажется, идут с кавычками
#    volumes:
#      - ./static:/static
#      - ./media:/media
#    depends_on:
#      - theatre-app

volumes:
  theatre_postgres_data:

networks:
  theatre_net:
    external: false


