# Generated by Django 4.2.7 on 2024-01-25 00:47

from django.db import migrations, models
import django.db.models.deletion
import radio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('speaker', models.CharField(max_length=255, verbose_name='Спикер')),
                ('image', models.ImageField(upload_to=radio.models.Audio.image_upload_to, verbose_name='Изображение')),
                ('audio', models.FileField(upload_to=radio.models.Audio.audio_upload_to, verbose_name='Аудиозапись')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Аудиозапись',
                'verbose_name_plural': 'Аудиозаписи',
            },
        ),
    ]
