# Generated by Django 4.2.7 on 2024-01-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_delete_personcategorys'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название категории')),
                ('block', models.CharField(blank=True, max_length=100, verbose_name='id блока')),
                ('sorting', models.IntegerField(verbose_name='Сортировка')),
            ],
        ),
    ]
