# Generated by Django 4.2.7 on 2024-01-25 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_personcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personcategory',
            options={'verbose_name': 'категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='person',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='people.personcategory', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
