# Generated by Django 4.2.7 on 2024-01-25 00:47

from django.db import migrations, models
import press.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('url', models.URLField(max_length=255, verbose_name='Ссылка на источник')),
                ('image', models.ImageField(blank=True, upload_to=press.models.Press.upload_to, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Пресса',
                'verbose_name_plural': 'Пресса',
            },
        ),
    ]
